### ISSUE TITLE
the media_animation saved to Arweave is not keeping the design

### ISSUE THREAD

**Issue by TheLubab** [curaOS/BSCS#46]
The `media_animation` link like this one below should always have the same design, but now when u refresh the page it changes
https://clo6zxqomato6re3yewy6wd2oubvxfj3uq6bxyb52mhzlgqx.arweave.net/Et3s3g5gJu9Em8Etj1h6dQNblT-u-kPBvgPdMPlZoXg

**Comment by bestatigen** [comment]
@achrafismyname could you write a description to make it more clear?

**Comment by TheLubab** [comment]
done @devey
