### ISSUE TITLE
Updated data is not appearing fast enough

### ISSUE THREAD

**Issue by AshenI99** [curaOS/BSCS#60]
When we perform an action like `remove_bid` or `mint`, it takes few seconds to get the updated data from the subgraph. 

- So in the `remove_bid` case, if the user tries to remove that bid again before it gets updated data from the subgraph, website is showing an error. That might confuse the user. 

- In the `mint` case, sometimes it needs several refreshes to the page before the newly minted token appear in the `explore` page.

**Comment by bestatigen** [comment]
@AshenI99 is this slowdown due to our front-end structure or just cause The Graph is slow at picking up updates to the contract?

**Comment by AshenI99** [comment]
> @AshenI99 is this slowdown due to our front-end structure or just cause The Graph is slow at picking up updates to the contract?

It is because of the caching method of apollo graphQL used in our frontend. I fixed it in the associated PR.
